stages:
  - mirror
  - stats
  - test
  - build
  - release

default:
  image: namboy94/ci-docker-environment:0.9.0
  before_script:
    - echo "$SERVER_ACCESS_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - apt install npm -y

github_mirror:
  stage: mirror
  tags: [docker]
  only: [master, develop]
  before_script:
    - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
  script:
    - git-mirror-pusher git@github.com:namboy94/anilist-enhancer.git
      master develop

gitstats:
  stage: stats
  tags: [docker]
  script:
    - gitstats-gen

stylecheck:
  stage: test
  tags: [docker]
  script:
    - webext-lint

build_addon:
  stage: build
  tags: [docker]
  script:
    - webext-build
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts/

sign_addon:
  stage: build
  only: [master]
  tags: [docker]
  script:
    - webext-build --signed
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts/

publish_addon:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - webext-build --signed --publish

release_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - github-release-upload $(webext-version) "$(changelog-reader)"
    - gitlab-release-upload $(webext-version) "$(changelog-reader)"
