stages:
  - mirror
  - stats
  - test
  - build
  - release

default:
  image: namboy94/ci-docker-environment:0.9.0
  before_script:
    - echo "$SERVER_ACCESS_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - apt install npm -y
    - npm install web-ext@4.2.0  # TODO Fix this

github_mirror:
  stage: mirror
  tags: [docker]
  only: [master, develop]
  before_script:
    - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
  script:
    - git-mirror-pusher git@github.com:namboy94/anilist-enhancer.git
      master develop

gitstats:
  stage: stats
  tags: [docker]
  script:
    - gitstats-gen

stylecheck:
  stage: test
  tags: [docker]
  script:
    - node_modules/.bin/web-ext lint -i virtual
    #- webext-lint TODO Fix this

build_addon:
  stage: build
  tags: [docker]
  script:
    - node_modules/.bin/web-ext build -i virtual
    #- webext-build TODO Fix this
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts/

sign_addon:
  stage: build
  only: [master]
  tags: [docker]
  script:
    - node_modules/.bin/web-ext sign --api-key "$JWT_ISSUER" --api-secret "$JWT_SECRET" -i virtual
    # - webext-build --signed TODO Fix this
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts/

publish_addon:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - node_modules/.bin/web-ext sign --api-key "$JWT_ISSUER" --api-secret "$JWT_SECRET" -i virtual --id "$AMO_ID"
    # - webext-build --signed --publish TODO Fix this

release_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - github-release-upload $(webext-version) "$(changelog-reader)"
    - gitlab-release-upload $(webext-version) "$(changelog-reader)"
